### ISSUE TITLE
【超絶緊急】日本語ディレクトリダメ

### ISSUE THREAD

**Issue by t-kusakabe** [SDisDark/SysDevMain#11]
# 日本語ディレクトリダメ

+ 基本的に全て英語で統一する
+ わかりやすい名前にしてね

**Comment by ahaha0807** [comment]
全員で共有しておきたいです。
日本語ディレクトリ・ファイル名
ダメ。絶対。

**Comment by ahaha0807** [comment]
なので、現状日本語になっているものはすべて英語名に直してください。
