### ISSUE TITLE
CheckoutScreen(決済画面)の決済確定の処理 がまだ

### ISSUE THREAD

**Issue by ahaha0807** [SDisDark/SysDevMain#130]
決済確定の処理 = URLに対してPOSTを使ってお預かり金額を送ることでサーバ内で処理して決済完了の場合、空室管理画面にリダイレクトする

**Comment by ahaha0807** [comment]
この画面いろいろ話があっちこっち飛んだんやけど、
確定としたいのが 
*サーバ内で計算した利用代金（部屋の種類、オプションをサーバのデータから計算）と、クライアントから送られてきた（決済画面で入力された値）を検証する*
ようにして欲しいのです

**Comment by s-Zenya** [comment]
計算した利用代金とクライアントから送られてきた金額を検証してTrueかｆａｌｓｅを返すだから
クライアントから送られてくる金額は利用代金と同じなことが前提、お釣りの計算とかはフロント側で行うっていう解釈でおｋですかね？
あと予約テーブルに決済状態列があるけどここの値も変えないといけ無さそう？

**Comment by ahaha0807** [comment]
同じなことが前提ですね。
それの確認のために計算したものと検証を行って欲しいのです。

で、お釣りの計算の解釈はそれでOK
予約テーブルの決済状態列な更新はよろしくお願いします！

**Comment by s-Zenya** [comment]
了解〜
たださっきPR見てたら#87ですでに宮前さんが作り始めてたっぽいけどどっちが担当しよう？

**Comment by ahaha0807** [comment]
うわっ！！
もうしわけない…完全に俺の見落としやわ…
これは宮前に任せてもうひとつの方 ( #131 )のほう見てもらってもいいかな…

**Comment by s-Zenya** [comment]
了解～
