### ISSUE TITLE
JPA を使って実装した DB クラスにアクセスできない

### ISSUE THREAD

**Issue by ahaha0807** [SDisDark/SysDevMain#30]
JPA を使って実装したDBのクラスをデバッグ&動作確認をしたいのに、Controllerから動かない

**Comment by r-miyamae** [comment]
何かDBのテーブルのカラム定義とクラスで作ったエンティティのカラム定義が違うからな気が

**Comment by r-miyamae** [comment]
persistence.xml内に
```
<class>jp.SysDev.database.EmployeeMasterDb</class>
```
のようにクラス指定したら動きました

**Comment by r-miyamae** [comment]
他のブランチでも動作確認しました

**Comment by ahaha0807** [comment]
何が悪かったんやろ…
すっごいもやもやする

**Comment by ahaha0807** [comment]
どんな感じ？

**Comment by t-kusakabe** [comment]
良きよ！

**Comment by r-miyamae** [comment]
どんな感じとは？？

**Comment by r-miyamae** [comment]
なんか<exclude-unlisted-classes>で自動でクラスが取得できてなかったくさい

**Comment by ahaha0807** [comment]
ブランチ変えても登録しないとダメやった？＆登録したら動いた？

**Comment by r-miyamae** [comment]
登録しないとダメ＆登録したら動作
っすね

**Comment by ahaha0807** [comment]
なるほど。
では登録する方向でやって行きますか…

**Comment by r-miyamae** [comment]
そうですね
一応<exclude-unlisted-classes>の仕様ちょっと調べてみます

**Comment by ahaha0807** [comment]
よろしくお願いします

**Comment by r-miyamae** [comment]
https://ml.seasar.org/archives/jpa/2007-May/000048.html
```<exclude-unlisted-classes>```いらない子説

**Comment by ahaha0807** [comment]
盲目的につけてたけど、何に使うようなやつでしょう…？

**Comment by r-miyamae** [comment]
JPA では，永続ユニットに含まれるエンティティクラスや
マッピングファイルを自動検出する機能があります．
それを抑止するには，persistence.xml に
<exclude-unlisted-classes> という要素を記述します．
この要素を使って，明示的に列挙したエンティティクラスや
マッピングファイル以外は使わないと言うことを
示すわけです．

**Comment by r-miyamae** [comment]
上のurlのコピペ

**Comment by ahaha0807** [comment]
抑止しちゃってたんか…。

**Comment by ahaha0807** [comment]
`<exclude-unlisted-classes>`
によって抑止するってこと？？

**Comment by r-miyamae** [comment]
本来trueにして使うっぽい
ただtrueにしてもエラーはら直らなかったでござる…

**Comment by r-miyamae** [comment]
ていうかtrueで抑止だから直らないのは当たり前か

無駄とはいえfalseでも動かなかったのが問題か

**Comment by ahaha0807** [comment]
exclude-unlisted-classesってことは「リストアップされていないクラスを除外」をfalseにするだでな

**Comment by ahaha0807** [comment]
明示的にfalse化してるだけやな

**Comment by r-miyamae** [comment]
そゆことっすね
ただ明示せずともしようとも動かないという謎

永続ユニットにｄｂクラスが入っていないてことかな？

**Comment by ahaha0807** [comment]
可能性があるな。
DBのクラスが認識されていない可能性

**Comment by r-miyamae** [comment]
ただ認識のさせ方がわからない件…
JPA仕様書の例ではclassタグで多数のデータベース結びつけてたんで取り敢えずそれで進めます

余裕があればまた解決策調べます

**Comment by ahaha0807** [comment]
安定するとのことなのですべてのDBクラス（Entityの定義クラス）は persistence.xml に登録する方向で作っていきましょうー
