### ISSUE TITLE
@Entity アノテーションが付与されていなかった問題

### ISSUE THREAD

**Issue by ahaha0807** [SDisDark/SysDevMain#36]
## Fixして欲しい内容
DBの定義を行うクラスに @Entity アノテーションが追加されていないので、ブランチを切ってFixして欲しいです 
## Fix対象ファイル
- CustomerTableDb
- ReceptionTableDb
- RoomStatementTableDb
- StatementMasterDb
## 対象者
@s-Zenya 
@r-miyamae 
## その他
二人で相談してもらって、完了したらまたPR送ってください。

**Comment by r-miyamae** [comment]
classのやつはPOJOだから良いってことで修正？
あとはs-zenkeにお願いします

**Comment by ahaha0807** [comment]
@r-miyamae どの話かいな…？
多分 OptionMgtKeyIdClass とかの話やったらそーです。
最初に書いてたけど、勘違いでした。すんません…

**Comment by s-Zenya** [comment]
@Entityの件申し訳ないでござんした
CustomerTableDb
ReceptionTableDb
RoomStatementTableDb
StatementMasterDb
これらについては修正しました

**Comment by s-Zenya** [comment]
あ、PRではなく普通にpushしました

**Comment by ahaha0807** [comment]
@s-Zenya 
修正ありがとう！
確認しやすくしたいから、PRの番号 (例: #XX)ってのをコメントで書いておいてくれると

**Comment by ahaha0807** [comment]
DONE！

**Comment by ahaha0807** [comment]
じゃなかった！！！
