### ISSUE TITLE
タイポ・クラス定義の間違いに気づいてませんでした。ごめんなさい

### ISSUE THREAD

**Issue by ahaha0807** [SDisDark/SysDevMain#37]
## Fix して欲しい内容
対象のファイルの記述ミスに気づいてませんでした。修正よろしくお願いします
## Fix 対象ファイル
- ReceptionTableDb
## Fix 対象行
- 15 MenberTableDb が存在してないです
- 29, 31, 33  EmployeeMaster が存在してないです
## 対象者
@s-Zenya 
## その他
レビューの時に気づいてませんでした。ごめんなさい…
Fixしてもらって、もう一度PRおねがいしますー…

**Comment by s-Zenya** [comment]
これってmasterをmergeすれば良いってこと？でしたら完了です

**Comment by ahaha0807** [comment]
いや、master をマージしてIntelliJ で開いたらわかると思うんやけど、対象行の部分、タイプミスしてて動いてないんよー…
