### ISSUE TITLE
【提案】PR見にくい

### ISSUE THREAD

**Issue by t-kusakabe** [SDisDark/SysDevMain#55]
PRどれがどれかわかんないので
+ サーバ側はメッセージの先頭に「server-メッセージ名」
+ フロント側はメッセージの先頭に「front-メッセージ名」
にしませんか！

**Comment by t-kusakabe** [comment]
@ahaha0807

**Comment by ahaha0807** [comment]
それはフロントサイドにもサーバサイドにもブロードキャストして徹底させるという形なら :+1: です

**Comment by t-kusakabe** [comment]
本件Lavelで解決いたしました。
