### ISSUE TITLE
デザインについて

### ISSUE THREAD

**Issue by t-kusakabe** [SDisDark/SysDevMain#83]
# topページ
+ 表示させる内容
  + お知らせ
  + 最新情報

# adminページ
## ヘッダーについて
+ font
+ 表示させる内容

## 空室管理画面について
+ レイアウト
+ 表示させる内容
### モーダル(空室管理画面の部屋情報)
+ 表示させる内容

**Comment by ahaha0807** [comment]
http://qiita.com/h-tko/items/e2a23beafed2315b56f8

**Comment by t-kusakabe** [comment]
# デザイン修正点

こちらのコメントに編集してリストっぽくしてくれると助かります！

**Comment by ahaha0807** [comment]
これ修正しても通知飛ばへんねんな

**Comment by ahaha0807** [comment]
再び通知
